### PR TITLE
Support for IDEA 2020.1

### PR DESCRIPTION
**Pull request by jborza**
Hi, 
I've upgraded the code according to the API changes (https://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2020.html).

The plugin is now compatible with IDEA 2020.1

Regards,
Juraj

### CODE REVIEW

**Comment by ziolko** [comment]
@jborza thanks for this pull request. As I am not actively maintaining this plugin I can make you a collaborator here and at https://plugins.jetbrains.com so that you can make changes and upload new plugin versions when needed. Are you OK with this?

**Comment by jborza** [comment]
Hi @ziolko ,
yes, that'd be great.
Thanks

**Comment by ziolko** [comment]
I've invited you to manage this repository. What's your login at https://plugins.jetbrains.com?

**Comment by jborza** [comment]
Hi,
Thanks for the invite.
It’s jborza@gmail.com

Regards,
Juraj

**Comment by ziolko** [comment]
Added you as a developer on the JetBrains portal. Feel free to credit yourself accordingly in this repo and on the plugin page :)

Cheers,
Mateusz

**Pull request merged**
